### PR TITLE
fixed 'TypError: quote_from_bytes() expected bytes' error on python3

### PR DESCRIPTION
**Pull request by hinnefe2**
Made a small edit that fixed a unicode vs bytes error I was getting when running using python3

This would probably resolve Issues #39 and #40

### CODE REVIEW

**Comment by rethore** [comment]
Thanks, that fixed the bug for me as well.

**Comment by ruthbarbaracimpa** [comment]
Thank you, it worked. same situation (win7, p3), the same issue.

**Comment by skyl** [comment]
Thank you, works for me.

**Comment by ckreibich** [comment]
Thanks for the fix, and apologies for the abysmal response times ...

**Pull request merged**
